package weissmoon;
import com.google.common.collect.Lists;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;

import java.util.List;

/**
 * Created by Weissmoon on 7/19/18.
 */
@Mod(modid = "JMFixer", name = "JMFixer", version = "1", dependencies = "after:journeymap", serverSideOnly = true)
public class JourneyMapFixer {
    @Mod.Instance
    private JourneyMapFixer INSTANCE;

    @Mod.EventHandler
    public void preInit (FMLPreInitializationEvent event) {
        ModMetadata md = event.getModMetadata();
        md.autogenerated = false;
        md.modId = "JMFixer";
        md.name = "JMFixer";
        List<String> autor = Lists.newArrayList();
        autor.add("Weissmoon");
        md.authorList = autor;
        md.version = "1";
        md.credits = "Elucent for creation of the logo and Albedo.";
        md.description = "Fixes #42";
    }
    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event){
        journeymap.common.network.PacketHandler.DIMENSION_PERMISSIONS_CHANNEL.registerMessage(journeymap.common.network.DimensionPermissionPacket.Listener.class, journeymap.common.network.DimensionPermissionPacket.class, 0, Side.CLIENT);
    }
}
